### ISSUE TITLE
change SHOULD to MUST 

### ISSUE THREAD

**Issue by mankamis** [ietf-wg-idr/draft-ietf-idr-link-bandwidth#3]
https://github.com/ietf-wg-idr/draft-ietf-idr-link-bandwidth/blob/60eca68b2e0f59edddf0363e501d3feaf0357d20/draft-ietf-idr-link-bandwidth.xml#L181

3.2.  Receiver (Receiving link bandwidth community)
 
   A BGP receiver MUST be able to process link bandwidth community of
   both transitive or non-transitive type.  The receiver SHOULD NOT flap
   or treat the route as malformed based on the transitivity of the link
   bandwidth community and/or BGP session type (internal vs.  external).
 

Keeping it should will leave chance of some implementation flapping the session. we make it MUST so it is sure that everyone behaves exactly same

**Comment by reshdas** [comment]
Fixed this issue. Please check
